### PR TITLE
Black Flag SRD - Monsters

### PR DESCRIPTION
**Pull request by crhallberg**
Picking up where #357 left off. Eager for help and feedback!

## Questions

- [x] Do I have to use a number for Document.pk?
  - [Looks like I do](https://discordapp.com/channels/470638316103008268/1110233912812245184/1220882704799891478)
- [x] Is `blackflag` the best slug and folder?

## TODO

- [x] Add Animals
- [x] Add NPCs
- [x] Add Lair Actions (not supported by v1)
- [x] Add Regional Effects (not supported by v1)
- [ ] Add v2
- [x] Confirm proper structure
- [x] Confirm proper monster attributes
- [x] Remove Monster.json_SKIPPED when done

## Tools

- [JS script for conversion](https://gist.github.com/crhallberg/49834ac184cdcc1e927193704559571b)
- [Black Flag SRD - Monsters.md](https://crhallberg.com/blackflag-srd/Black%20Flag%20SRD%20-%20Monsters.md)
- [Black Flag SRD - Monsters (html)](https://crhallberg.com/blackflag-srd/monsters.html)

### CODE REVIEW

**Comment by eepMoody** [comment]
I can't figure out why it isn't reporting back here, but the error on docker hub is that one of the creatures in the JSON is missing its "speed" key. But the output on Docker Hub doesn't include a line number, so it could be anywhere. I'm not sure how best to find it 😭

**Comment by crhallberg** [comment]
Thank you! I'll look into it! Yeah, the Docker thing baffled me too. I apparently just cause *the best* errors. Accept no substitute!

**Comment by crhallberg** [comment]
I see the issue. The [v1 Monster model](https://github.com/open5e/open5e-api/blob/staging/api/models/monster.py) has no speed attribute. So I have it when I shouldn't! Save it for v2, I guess!

**Comment by crhallberg** [comment]
Alright! This is now successfully building in my local instance!

**Comment by crhallberg** [comment]
Thanks @mshea for the Markdown files, it's helping me catch formatting issues where my regex didn't catch Action titles, etc. Gonna resolve all the diffs today!

**Comment by crhallberg** [comment]
Should I address v2 conversion in another PR? If the site is still using v1, I don’t want to delay making this material available. cc @eepMoody

**Comment by eepMoody** [comment]
@crhallberg Hey! We finally figured out the answer to your question! We're going to merge this in as-is, and then do the v2 version via some automation!

**Review by eepMoody — APPROVED** [review]

**Pull request merged**
