### PR TITLE
Lots of dependencies updated

### PR DESCRIPTION
**Pull request by augustjohnson**
Updated python from 3.8 to 3.10, and pinned it.
Updated django to 3.2.18 and pinned it to 3.
Updated literally everything else, and set them to *
Adjusted filters to now use filtersets (per new version of drf). More info here: https://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend
Removed a couple of urls.py methods that will be deprecated in django4.

**Tested by:**
All root endpoints load visibly correctly and without error.
localhost:8000/spells/?slug__in=magic-missile producing the same results as production.
Ordering by different values produces expected results on monsters.
Pagination appears to be the same as before.
The Options button seems to work as expected.
Filters appear on all of the endpoints' pages' modal popup, and appear to be (spot-check) working.

Update your dependencies folks!

### CODE REVIEW

**Comment by augustjohnson** [comment]
Should fix https://github.com/open5e/open5e-api/issues/116
FYI I picked python 3.10 because 3.11 is not yet available on digital ocean's app platform.  I figured support-wise it was probably more broadly supported.
https://docs.digitalocean.com/products/app-platform/

**Comment by augustjohnson** [comment]
Will resolve https://github.com/open5e/open5e-api/pull/111

**Comment by eepMoody** [comment]
@augustjohnson looks like this hit an issue in docker cloud. Error was:

```bash
2023-03-21T02:56:57Z #12 [6/8] RUN pipenv install
2023-03-21T02:56:58Z #12 1.381 Loading .env environment variables...
2023-03-21T02:56:58Z #12 1.778 Warning: Python 3.10 was not found on your system...
2023-03-21T02:56:58Z #12 1.781 Neither 'pyenv' nor 'asdf' could be found to install Python.
2023-03-21T02:56:58Z #12 1.781 You can specify specific versions of Python with:
2023-03-21T02:56:58Z #12 1.781 $ pipenv --python path/to/python
2023-03-21T02:56:58Z #12 ERROR: executor failed running [/bin/sh -c pipenv install]: exit code: 1
2023-03-21T02:56:58Z ------
2023-03-21T02:56:58Z > [6/8] RUN pipenv install:
2023-03-21T02:56:58Z #12 1.381 Loading .env environment variables...
2023-03-21T02:56:58Z #12 1.778 Warning: Python 3.10 was not found on your system...
2023-03-21T02:56:58Z #12 1.781 Neither 'pyenv' nor 'asdf' could be found to install Python.
2023-03-21T02:56:58Z #12 1.781 You can specify specific versions of Python with:
2023-03-21T02:56:58Z #12 1.781 $ pipenv --python path/to/python
2023-03-21T02:56:58Z ------
2023-03-21T02:56:58Z ERROR: failed to solve: executor failed running [/bin/sh -c pipenv install]: exit code: 1
2023-03-21T02:56:58Z Build failed using Buildkit (1)
```

**Comment by Gredelston** [comment]
Nice work! I'm looking forward to these upgrades.

> FYI I picked python 3.10 because 3.11 is not yet available on digital ocean's app platform. I figured support-wise it was probably more broadly supported.
> https://docs.digitalocean.com/products/app-platform/

I disagree. The [full release notes](https://docs.digitalocean.com/release-notes/app-platform/) show that Python 3.11 support was added in January 2022. It just doesn't appear on the page you linked because that page only shows the most recent release notes, which did not add any _additional_ 3.11 support. Py3.11 is the current stable version, so it should be broadly supported.

**Comment by augustjohnson** [comment]
@eepMoody That's predictable, my fault, I was pretty focused on the django-only environment.  I'll work to upgrade that, but I haven't fiddled with docker on my side. I'm glad we have the tests in place.

@Gredelston wow my reading skills were lacking. That's what I get for staying up past bedtime.  I will target 3.11 for my next set of changes.

**Comment by augustjohnson** [comment]
To do:
1. Update and test python_version=3.11 in the Pipfile. Test.
2. Change our base image to be one that includes python 3.11 Test.

For 2, I will likely just adjust the FROM in the dockerfile to be: FROM python:3.11. The big change to alpine or whatever is down the road a step or two, not part of this.

**Comment by augustjohnson** [comment]
Actually holy crap, I may try: python:3.11-alpine (which uses alpine as the base!) that could be a great place to start. Officially provided by python, but reliably based on the alpine image!

**Comment by augustjohnson** [comment]
This is a **BIG FAT** change. When merging/deploying we should have a rollback plan.
Also, something to keep in mind, since I set it to * for most of the dependencies, these will change over time to the latest stable. Which is a good thing, but potentially adds a bit of instability.

**Comment by eepMoody** [comment]
@augustjohnson How about we switch this to merge to `staging` first then?

Docker Hub is already set to build an alternate image from that branch. I can make sure the other droplet pulls from it and builds successfully first, and we can poke at it for a bit before we merge it into Master?

**Comment by augustjohnson** [comment]
Just changed base.

**Comment by eepMoody** [comment]
Merge away at your convenience, and feel free to push stuff straight up to staging if you need to tweak stuff. It's intentionally not a protected branch.

**Pull request merged**
