### PR TITLE
Black flag SRD content

### PR DESCRIPTION
**Pull request by Sturlen**
First pass on parsing the Black Flag Reference Document. Currently only monsters. Parsing is not yet fully complete, so some monsters are quite broken. Needs proper license/document too.

Based on issue #338

### CODE REVIEW

**Comment by augustjohnson** [comment]
This has been merged to release/1.4.0 by #382

**Comment by crhallberg** [comment]
Are you looking for help parsing the rest of the monsters? Or transcribing the rules?

**Comment by crhallberg** [comment]
If it's helpful, I've reformatted the Monster section of the Black Flag SRD into Markdown. You can see the [raw .md file here](https://crhallberg/Black Flag SRD - Monsters.md) and the [parsed HTML here](https://crhallberg/Black Flag SRD - Monsters.html).

Today, I also found out that Kobold Press has the SRD in Foundry format up on GitHub: https://github.com/koboldpress/black-flag.

**Comment by augustjohnson** [comment]
This appears to be completed.

**Pull request closed without merging**
