### PR TITLE
Adding page numbers based on the SRD PDF

### PR DESCRIPTION
**Pull request by augustjohnson**

### CODE REVIEW

**Review by eepMoody — APPROVED** [review]

**Comment by augustjohnson** [comment]
Hey there's some weird unicode characters in this... take a triple check before merging. I'm not sure I MEANT to commit those, will those cause problems?

**Comment by eepMoody** [comment]
@augustjohnson Yeah, I _think_ those will be fine, but for the sake of consistency would you mind trying to find and replace them back to the actual bullet character?

Like I think our setup will digest them just fine, but other people may not be parsing them out.

**Review by eepMoody — CHANGES_REQUESTED** [review]
Can we switch these bullets back, just for the sake of consistency? I'm not sure our build will be affected, but others might be expecting them, especially if they're doing any parsing of the spellcaster info.

**Comment by augustjohnson** [comment]
Yep, should be fine now.

**Review by eepMoody — APPROVED** [review]

**Pull request merged**
