### PR TITLE
Added missing data for the Deck Of Many Things card descriptions.

### PR DESCRIPTION
**Pull request by bruno-71**
Item descriptions after the Skull card were missing.  Added the missing card descriptions.

### CODE REVIEW

**Review by eepMoody — CHANGES_REQUESTED** [review]
Remove add'l whitespace on each line

**Comment by bruno-71** [comment]
I think the issue was that Prettier changed the tabs to spaces.  Sorry about that, I'm still new to open source.  Hopefully that last push fixed it.

**Comment by augustjohnson** [comment]
FYI I have merged these changes into the working branch release/1.4.0

**Comment by augustjohnson** [comment]
Available on beta here.
https://beta.open5e.com/magic-items/deck-of-many-things

**Pull request closed without merging**
