### PR TITLE
Added Barbarian subclasses from Tome of Heroes

### PR DESCRIPTION
**Pull request by JonathanELawrence**
classes.json & document.json

### CODE REVIEW

**Comment by JonathanELawrence** [comment]
Commit **85f6b1b** also added Rogue

**Review by augustjohnson — CHANGES_REQUESTED** [review]
I'd like to collaborate on getting these in. There's at least 1 bug to fix. I've changed the base branch that you're requesting a merge into to open5e:tome-of-heroes so that I can work on it a bit after we merge before it's time for staging.

I do require some changes though!

Please adjust classes.json to NOT include (class level) fields, or subclasses that are part of the SRD.  Your file should start off like this:

[
    {
        "name": "Barbarian",
        "subtypes": [
            {
                "name": "Path of Booming Magnificence",

**Comment by JonathanELawrence** [comment]
Thanks August. These changes have been implemented and all subclasses have been added.

**Comment by augustjohnson** [comment]
Merging, but this doesn't actually do anything yet.  It's on me to get this to appropriately import, and I'll do it in the tome-of-heroes branch.

**Pull request merged**
